### ISSUE TITLE
DocTub is not-responsive on first painting

### ISSUE THREAD

**Issue by sivaramakrishnan004** [doctub/issues#2]
**[DocTub](https://doctub.com)** is **not-responsive** on first painting because CSS aand JS are not loaded properly from **_CACHE_** or by **_SERVICE-WORKER_**, Please work on this issue.

**Comment by yoginth** [comment]
Soon this issue will be fixed, we don't know the correct **ETA**! and sorry for this inconvenience!

**Comment by yoginth** [comment]
The issue has been fixed, by updating rocketscript and updated browser cache TTL. This issue will be open for 2 days if any contact us.
